### ISSUE TITLE
Nuevo concepto de parser

### ISSUE THREAD

**Issue by tory1103** [ZSendokame/dsl#1]
He estado mirando tu parser y he encontrado varias mejoras por hacer, las numerare:

1) Separar el contenido de la linea de codigo en dos partes : En vez de usar regex, porque no lo separas con ':', de esta forma separarias el codigo en dos partes, es decir: 
      str juan : 'hola mundo q tal' -> se dividira en argumentos ( .split(":")[0] = str juan ) y valor ( .split(":")[1:] )
de esta forma sera mucho mas facil analizar los datos y sacar conclusiones

2) No cargar todo el codigo de golpe, sino linea por linea

3) Anadir mas tipos de datos como los float ( ya se que funciona con los int, pero es confuso)  o las arrays

**Comment by ZSendokame** [comment]
Si hago un split con ":" me devolveria str.valor, lo segundo no lo entiendo ya que el code es spliteado por \n (Lo cual me deja un array que itero linea por linea para analizarlo), en cuanto lo tercero ya estoy trabajando en arrays

**Comment by tory1103** [comment]
He hecho un PR explicando como seria el nuevo parser
